# Generated by Django 5.2.15 on 2026-06-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='EM_ANDAMENTO', max_length=20)),
                ('total_baixados', models.IntegerField(default=0)),
                ('total_ja_existentes', models.IntegerField(default=0)),
                ('total_nao_encontrados', models.IntegerField(default=0)),
                ('log_texto', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Execução do Scraper',
                'verbose_name_plural': 'Execuções do Scraper',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
