# Generated by Django 5.2.15 on 2026-06-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctbuscador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoscraper',
            name='abortar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='execucaoscraper',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execucaoscraper',
            name='status',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro'), ('ABORTADO', 'Abortado')], default='EM_ANDAMENTO', max_length=20),
        ),
    ]
