# Generated by Django 5.2.15 on 2026-06-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctbuscador', '0002_execucaoscraper_abortar_execucaoscraper_pid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoscraper',
            name='nao_encontrados_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
