# Generated by Django 5.2.15 on 2026-06-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctbuscador', '0003_execucaoscraper_nao_encontrados_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoScraper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('horario', models.TimeField(help_text='Horário de execução (HH:MM)')),
                ('recorrencia', models.CharField(choices=[('DIARIA', 'Diária'), ('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal')], default='DIARIA', max_length=20)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], help_text='Obrigatório apenas para recorrência semanal', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='Obrigatório apenas para recorrência mensal (1-31)', null=True)),
                ('headless', models.BooleanField(default=True, verbose_name='Headless')),
                ('sindicato_codigo', models.CharField(blank=True, help_text='Deixe em branco para processar todos os sindicatos', max_length=20, verbose_name='Código do Sindicato')),
                ('forcar', models.BooleanField(default=False, verbose_name='Forçar re-download')),
                ('ultima_execucao', models.DateTimeField(blank=True, null=True)),
                ('proxima_execucao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Agendamento do Scraper',
                'verbose_name_plural': 'Agendamentos do Scraper',
                'ordering': ['horario'],
            },
        ),
    ]
