# Generated by Django 5.2.15 on 2026-06-25 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=20, unique=True)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=14)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sindicato',
                'verbose_name_plural': 'Sindicatos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CCT', 'CCT'), ('TA-CCT', 'TA-CCT')], max_length=10)),
                ('data_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('data_fim_vigencia', models.DateField(blank=True, null=True)),
                ('arquivo_pdf', models.CharField(blank=True, max_length=500)),
                ('data_base', models.DateField(blank=True, null=True)),
                ('reajuste_percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('contribuicao_sindical_empregado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contribuicao_sindical_patronal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_extracao', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EXTRAIDO', 'Extraído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('sindicato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cctcore.sindicato')),
            ],
            options={
                'verbose_name': 'Documento CCT',
                'verbose_name_plural': 'Documentos CCT',
                'ordering': ['-data_inicio_vigencia', 'sindicato', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaSindicato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sindicatos', to='cctcore.empresa')),
                ('sindicato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='cctcore.sindicato')),
            ],
            options={
                'verbose_name': 'Relação Empresa-Sindicato',
                'verbose_name_plural': 'Relações Empresa-Sindicato',
                'unique_together': {('empresa', 'sindicato')},
            },
        ),
    ]
