# Generated by Django 5.2.15 on 2026-06-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocct',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
