# Generated by Django 5.2.15 on 2026-06-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0002_documentocct_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_api_opencode', models.CharField(blank=True, max_length=255, verbose_name='Chave API OpenCode Go')),
                ('modelo_padrao_opencode', models.CharField(default='kimi-k2.6', max_length=50, verbose_name='Modelo padrão OpenCode Go')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
        migrations.AddField(
            model_name='documentocct',
            name='analise_ia_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentocct',
            name='analise_ia_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentocct',
            name='data_analise_ia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentocct',
            name='status_analise_ia',
            field=models.CharField(blank=True, choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20),
        ),
    ]
