# Generated by Django 5.2.15 on 2026-06-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0003_configuracaosistema_documentocct_analise_ia_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='prompt_analise_cct',
            field=models.TextField(blank=True, default="Analise a seguinte Convenção Coletiva de Trabalho (CCT) e extraia:\n1. data_base (data-base da negociação)\n2. vigencia_inicio (início da vigência)\n3. vigencia_fim (fim da vigência)\n4. reajuste_percentual (percentual de reajuste salarial, se houver)\n5. contribuicao_sindical_empregado (valor ou percentual da contribuição sindical/negocial dos empregados)\n6. contribuicao_sindical_patronal (valor ou percentual da contribuição patronal, se houver)\n7. pisos_salariais (lista de funções e seus respectivos pisos salariais)\n8. beneficios (lista de benefícios mencionados com breve descrição)\n9. jornada (informações sobre jornada de trabalho, se houver algo específico)\n10. aviso_previo (regras de aviso prévio, se houver algo específico)\n11. multa (regras de multa, se houver algo específico)\n12. outras_clausulas_relevantes (outras cláusulas que considerar importantes)\n\nResponda em JSON com EXATAMENTE essas chaves. Use null quando não encontrar a informação. No campo 'resumo', faça um breve resumo de 3 a 5 linhas da CCT.\n\nTEXTO DA CCT:\n{texto_cct}", help_text='Prompt enviado à IA para análise das CCTs. Use {texto_cct} como placeholder para o texto extraído do PDF.', verbose_name='Prompt para análise de CCT'),
        ),
    ]
