# Generated by Django 5.2.15 on 2026-06-30 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0004_configuracaosistema_prompt_analise_cct'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaDocumentoCCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculadas', to='cctcore.documentocct')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cct', to='cctcore.empresa')),
            ],
            options={
                'verbose_name': 'CCT Vinculada à Empresa',
                'verbose_name_plural': 'CCTs Vinculadas às Empresas',
                'unique_together': {('empresa', 'documento')},
            },
        ),
    ]
