# Generated by Django 5.2.15 on 2026-07-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0005_empresadocumentocct'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocct',
            name='data_registro_mte',
            field=models.DateField(blank=True, null=True, verbose_name='Data de registro no MTE'),
        ),
        migrations.AddField(
            model_name='sindicato',
            name='data_ultima_busca',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última busca'),
        ),
        migrations.AddField(
            model_name='sindicato',
            name='sem_documentos',
            field=models.BooleanField(default=False, verbose_name='Sem documentos na última busca'),
        ),
    ]
