# Generated by Django 5.2.15 on 2026-07-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0006_documentocct_data_registro_mte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocct',
            name='contribuicao_sindical_empregado_meses',
            field=models.CharField(blank=True, help_text="Meses em que a contribuição é descontada (ex: MAR, MAI, AGO, OUT ou '12x ao ano')", max_length=100, null=True, verbose_name='Meses desconto contrib. sindical/negocial'),
        ),
    ]
