# Generated by Django 5.2.15 on 2026-07-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0007_documentocct_contribuicao_sindical_empregado_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
    ]
