# Generated by Django 5.2.15 on 2026-07-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0008_empresa_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocct',
            name='trecho_contribuicao_empregado',
            field=models.TextField(blank=True, help_text='Texto original da CCT referente à contribuição sindical/negocial dos empregados', null=True, verbose_name='Trecho contribuição empregado'),
        ),
        migrations.AddField(
            model_name='documentocct',
            name='trecho_contribuicao_patronal',
            field=models.TextField(blank=True, help_text='Texto original da CCT referente à contribuição sindical/negocial patronal', null=True, verbose_name='Trecho contribuição patronal'),
        ),
    ]
