# Generated by Django 5.2.15 on 2026-08-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0009_documentocct_trecho_contribuicao_empregado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosistema',
            name='emails_internos',
            field=models.TextField(blank=True, default='', help_text='Informe um e-mail por linha ou separados por vírgula.', verbose_name='E-mails internos para avisos de novas CCTs'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='convencao_aplicada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_como_aplicado', to='cctcore.documentocct', verbose_name='Convenção aplicada'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail do cliente'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sindicato_aplicado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_como_aplicado', to='cctcore.sindicato', verbose_name='Sindicato aplicado'),
        ),
        migrations.CreateModel(
            name='NotificacaoDocumentoCCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('ERRO', 'Erro')], db_index=True, default='PENDENTE', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('enviada_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='cctcore.documentocct')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'criada_em'], name='cctcore_not_status_c3c02e_idx')],
                'constraints': [models.UniqueConstraint(fields=('documento', 'destinatario'), name='uniq_notif_doc_dest')],
            },
        ),
    ]
