# Generated by Django 5.2.15 on 2026-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0010_configuracaosistema_emails_internos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sindicato',
            name='apelido',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
