# Generated by Django 5.2.15 on 2026-08-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctcore', '0011_add_apelido_sindicato'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentocct',
            name='contribuicao_sindical_empregado_meses_manual',
            field=models.CharField(blank=True, help_text="Mês(ses) de desconto inserido manualmente. Ex: MAR, MAI, AGO, OUT ou '12x ao ano'", max_length=100, null=True, verbose_name='Meses desconto (manual)'),
        ),
        migrations.AddField(
            model_name='documentocct',
            name='trecho_contribuicao_empregado_manual',
            field=models.TextField(blank=True, help_text='Texto inserido manualmente pelo usuário. Quando preenchido, sobrescreve o trecho extraído automaticamente.', null=True, verbose_name='Trecho contribuição empregado (manual)'),
        ),
        migrations.AddField(
            model_name='documentocct',
            name='trecho_contribuicao_patronal_manual',
            field=models.TextField(blank=True, help_text='Texto inserido manualmente pelo usuário. Quando preenchido, sobrescreve o trecho extraído automaticamente.', null=True, verbose_name='Trecho contribuição patronal (manual)'),
        ),
        migrations.AddField(
            model_name='documentocct',
            name='usa_meses_manual',
            field=models.BooleanField(default=False, help_text='Quando ativo, o mês de desconto manual sobrescreve o extraído automaticamente.', verbose_name='Usar mês de desconto manual'),
        ),
        migrations.AddField(
            model_name='documentocct',
            name='usa_trechos_manuais',
            field=models.BooleanField(default=False, help_text='Quando ativo, os trechos de contribuição manual sobrescrevem os extraídos automaticamente.', verbose_name='Usar trechos manuais'),
        ),
    ]
